image: node:10

before_script:
  - which npm
  - npm -v
  - npm install
  - npm install --no-save yarn
  - node_modules/.bin/yarn install

stages:
  - test
  - build

test:
  stage: test
  script: npm test

build:
  stage: build
  script: npm run build
