image: node:10

before_script:
  - which npm
  - npm -v
  - which yarn
  - yarn -v
  - yarn install

stages:
  - test
  - build

test:
  stage: test
  script: npm test

build:
  stage: build
  script: npm run build
